spring:
  application:
    name: OrderService
  profiles:
    active: dev
  config:
    import: optional:configserver:http://admin:1234@localhost:9000

# server.port: 7001

# logging:
#   level:
#     root: INFO
#     com.msa.microservices: DEBUG